### ISSUE TITLE
Object Landing behind an occlusion/obstacle after drop

### ISSUE THREAD

**Issue by shivanimall** [intuitivecomputing/Object_Permanence_through_AudioVisual_Representations#1]
Hello, 

Thank you for this great work and making the codebase available. I wonder if you capture the case in which an object accidentally drops and lands behind an occlusion or an obstacle such that vision sensor can't see such an object?

Thanks, please let me know if my question is unclear!

**Comment by FrankBu0616** [comment]
Hi! Thank you for reaching out to us. Our paper is available at https://arxiv.org/pdf/2010.09948.pdf. As you can see in figure 1, we did not include any obstacles in the setup. However, the vision sensor we used has a limited view, thus it does not capture object's whole trajectory (visual sensor can't see the object after the object bounces out of sensor's visual field.) I hope this is helpful! Let me know if you have any further questions!
